[features]
seeds = true
skip-lint = false
[programs.localnet]
bump_seed_canonicalization = "HEeTz7bVJ5qSeTsPREXcyg6KCVjKW1gLogVaGXR6cwvU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
